# Introduction on Open science {-}
## Presentation {-}


```{r embed-xaringan, echo=FALSE}

embed_xaringan(url = "slides/00-Open-science/index.html", ratio = "16:9")

```


## Goals of the Seance {-}


>The main  goal of this module is to enable the students to konw the fundamentals of the scientific research. So, 

Ce module a pour objectif de permettre aux étudiants de maîtriser les bases de la recherche scientifique : recherche documentaire ciblée, analyse de documents (essentiellement en langue Anglaise), synthèse sous la forme de la rédaction d’un article, préparer et suivre un protocole expérimental et aussi l’organisation et les modes de financement de la recherche. Le module est organisé en deux volets : méthodologie de recherche et atelier d’écriture


## Intended course learning outcomes {-}

After having taking this module, you should be able to:


 
## ARCHE or not ARCHE?


### Acknowledgments {.appendix} {-}

This module is always a *Working in Progress*. 
Given the fact that you will use it, and undertand, let us know you opinion on github. 




