
# (PART\*) Annexes {-}

# Software installation in local machine {-}

## Setup 2 (For Warriors)

If you feel capable to take the path of the warrior..

### Installing Git in your machine

1. Go to Git https://git-scm.com/downloads
2. Install you according to your machine (Windows, MacOs, Linux)
3. Eventually install github desktop


### Install R {-}

1. Go to R-Project https://www.r-project.org/ and click on [download R](http://cran.r-project.org/mirrors.html).
2. Go to France, and select a Mirror (Univ-lyon works normally well!)
3. Download according your machine and install

### Rstudio {-}

1. You can install R Studio on your own machine from: https://www.rstudio.com/products/rstudio/download/#download

RStudio is a free and open-source integrated development environment for R 

So, two options are proposed. **Please, do these steps before the day of the workshop**.
If questions or problems, let us know as soon as possible


Before the day of the course, we advise you to get functional access to these software / and platforms. 



